export { default as Text } from "./Text.svelte";
export { default as Strong } from "./Strong.svelte";
export { default as Heading } from "./Heading.svelte";
export { default as Blockquote } from "./Blockquote.svelte";
export { default as Code } from "./Code.svelte";
export { default as Em } from "./Em.svelte";
export { default as Kbd } from "./Kbd.svelte";
export { default as Link } from "./Link.svelte";
export { default as Quote } from "./Quote.svelte";